Add delete all lessons of a person function
AY2425S1-CS2103-F11-2/tp pull request #71
Opened 2024-10-14 15:05 UTC by ethantyh692

2024-10-14 15:34 UTC, NorbertLoh reviewed
Nits to fix. Otherwise LGTM!

2024-10-14 15:34 UTC, NorbertLoh commented on src/main/java/tutorease/address/model/Model.java
> +     */
perhaps right this in the javadoc form with the parameter.
```suggestions
/**
* Deletes all the lessons of a particular student
*
* @param student The person object to look up.
*/

2024-10-14 15:52 UTC, Chronoxy requested changes
LGTM! However, some checks seems to be failing, can take a look and fix them before we merge

2024-10-14 16:23 UTC, ethantyh692 commented
> LGTM! However, some checks seems to be failing, can take a look and fix them before we merge

Haven't tested this new function yet so the checks are failing. Will create new issue for junit once merged.

2024-10-15 03:10 UTC, NorbertLoh commented
Perhaps you can override it and just make it return null for now and implement it later. So that our checks do not let any possible issues go through for this PR.

2024-10-15 09:08 UTC, ethantyh692 commented
> Perhaps you can override it and just make it return null for now and implement it later. So that our checks do not let any possible issues go through for this PR.

@NorbertLoh @Chronoxy errors fixed

2024-10-15 12:43 UTC, merged